# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trimsky/AsciiMachine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trimsky/AsciiMachine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trimsky/AsciiMachine/CMakeFiles /home/trimsky/AsciiMachine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trimsky/AsciiMachine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ascii

# Build rule for target.
Ascii: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ascii
.PHONY : Ascii

# fast build rule for target.
Ascii/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/build
.PHONY : Ascii/fast

AsciiMachineCurrent/API/src/AsciiSignal.o: AsciiMachineCurrent/API/src/AsciiSignal.cpp.o
.PHONY : AsciiMachineCurrent/API/src/AsciiSignal.o

# target to build an object file
AsciiMachineCurrent/API/src/AsciiSignal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/AsciiSignal.cpp.o
.PHONY : AsciiMachineCurrent/API/src/AsciiSignal.cpp.o

AsciiMachineCurrent/API/src/AsciiSignal.i: AsciiMachineCurrent/API/src/AsciiSignal.cpp.i
.PHONY : AsciiMachineCurrent/API/src/AsciiSignal.i

# target to preprocess a source file
AsciiMachineCurrent/API/src/AsciiSignal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/AsciiSignal.cpp.i
.PHONY : AsciiMachineCurrent/API/src/AsciiSignal.cpp.i

AsciiMachineCurrent/API/src/AsciiSignal.s: AsciiMachineCurrent/API/src/AsciiSignal.cpp.s
.PHONY : AsciiMachineCurrent/API/src/AsciiSignal.s

# target to generate assembly for a file
AsciiMachineCurrent/API/src/AsciiSignal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/AsciiSignal.cpp.s
.PHONY : AsciiMachineCurrent/API/src/AsciiSignal.cpp.s

AsciiMachineCurrent/API/src/Color.o: AsciiMachineCurrent/API/src/Color.cpp.o
.PHONY : AsciiMachineCurrent/API/src/Color.o

# target to build an object file
AsciiMachineCurrent/API/src/Color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Color.cpp.o
.PHONY : AsciiMachineCurrent/API/src/Color.cpp.o

AsciiMachineCurrent/API/src/Color.i: AsciiMachineCurrent/API/src/Color.cpp.i
.PHONY : AsciiMachineCurrent/API/src/Color.i

# target to preprocess a source file
AsciiMachineCurrent/API/src/Color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Color.cpp.i
.PHONY : AsciiMachineCurrent/API/src/Color.cpp.i

AsciiMachineCurrent/API/src/Color.s: AsciiMachineCurrent/API/src/Color.cpp.s
.PHONY : AsciiMachineCurrent/API/src/Color.s

# target to generate assembly for a file
AsciiMachineCurrent/API/src/Color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Color.cpp.s
.PHONY : AsciiMachineCurrent/API/src/Color.cpp.s

AsciiMachineCurrent/API/src/Entity.o: AsciiMachineCurrent/API/src/Entity.cpp.o
.PHONY : AsciiMachineCurrent/API/src/Entity.o

# target to build an object file
AsciiMachineCurrent/API/src/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Entity.cpp.o
.PHONY : AsciiMachineCurrent/API/src/Entity.cpp.o

AsciiMachineCurrent/API/src/Entity.i: AsciiMachineCurrent/API/src/Entity.cpp.i
.PHONY : AsciiMachineCurrent/API/src/Entity.i

# target to preprocess a source file
AsciiMachineCurrent/API/src/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Entity.cpp.i
.PHONY : AsciiMachineCurrent/API/src/Entity.cpp.i

AsciiMachineCurrent/API/src/Entity.s: AsciiMachineCurrent/API/src/Entity.cpp.s
.PHONY : AsciiMachineCurrent/API/src/Entity.s

# target to generate assembly for a file
AsciiMachineCurrent/API/src/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Entity.cpp.s
.PHONY : AsciiMachineCurrent/API/src/Entity.cpp.s

AsciiMachineCurrent/API/src/GUI_o.o: AsciiMachineCurrent/API/src/GUI_o.cpp.o
.PHONY : AsciiMachineCurrent/API/src/GUI_o.o

# target to build an object file
AsciiMachineCurrent/API/src/GUI_o.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/GUI_o.cpp.o
.PHONY : AsciiMachineCurrent/API/src/GUI_o.cpp.o

AsciiMachineCurrent/API/src/GUI_o.i: AsciiMachineCurrent/API/src/GUI_o.cpp.i
.PHONY : AsciiMachineCurrent/API/src/GUI_o.i

# target to preprocess a source file
AsciiMachineCurrent/API/src/GUI_o.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/GUI_o.cpp.i
.PHONY : AsciiMachineCurrent/API/src/GUI_o.cpp.i

AsciiMachineCurrent/API/src/GUI_o.s: AsciiMachineCurrent/API/src/GUI_o.cpp.s
.PHONY : AsciiMachineCurrent/API/src/GUI_o.s

# target to generate assembly for a file
AsciiMachineCurrent/API/src/GUI_o.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/GUI_o.cpp.s
.PHONY : AsciiMachineCurrent/API/src/GUI_o.cpp.s

AsciiMachineCurrent/API/src/Scene.o: AsciiMachineCurrent/API/src/Scene.cpp.o
.PHONY : AsciiMachineCurrent/API/src/Scene.o

# target to build an object file
AsciiMachineCurrent/API/src/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Scene.cpp.o
.PHONY : AsciiMachineCurrent/API/src/Scene.cpp.o

AsciiMachineCurrent/API/src/Scene.i: AsciiMachineCurrent/API/src/Scene.cpp.i
.PHONY : AsciiMachineCurrent/API/src/Scene.i

# target to preprocess a source file
AsciiMachineCurrent/API/src/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Scene.cpp.i
.PHONY : AsciiMachineCurrent/API/src/Scene.cpp.i

AsciiMachineCurrent/API/src/Scene.s: AsciiMachineCurrent/API/src/Scene.cpp.s
.PHONY : AsciiMachineCurrent/API/src/Scene.s

# target to generate assembly for a file
AsciiMachineCurrent/API/src/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Scene.cpp.s
.PHONY : AsciiMachineCurrent/API/src/Scene.cpp.s

AsciiMachineCurrent/API/src/Server.o: AsciiMachineCurrent/API/src/Server.cpp.o
.PHONY : AsciiMachineCurrent/API/src/Server.o

# target to build an object file
AsciiMachineCurrent/API/src/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Server.cpp.o
.PHONY : AsciiMachineCurrent/API/src/Server.cpp.o

AsciiMachineCurrent/API/src/Server.i: AsciiMachineCurrent/API/src/Server.cpp.i
.PHONY : AsciiMachineCurrent/API/src/Server.i

# target to preprocess a source file
AsciiMachineCurrent/API/src/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Server.cpp.i
.PHONY : AsciiMachineCurrent/API/src/Server.cpp.i

AsciiMachineCurrent/API/src/Server.s: AsciiMachineCurrent/API/src/Server.cpp.s
.PHONY : AsciiMachineCurrent/API/src/Server.s

# target to generate assembly for a file
AsciiMachineCurrent/API/src/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/Server.cpp.s
.PHONY : AsciiMachineCurrent/API/src/Server.cpp.s

AsciiMachineCurrent/API/src/utils.o: AsciiMachineCurrent/API/src/utils.cpp.o
.PHONY : AsciiMachineCurrent/API/src/utils.o

# target to build an object file
AsciiMachineCurrent/API/src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/utils.cpp.o
.PHONY : AsciiMachineCurrent/API/src/utils.cpp.o

AsciiMachineCurrent/API/src/utils.i: AsciiMachineCurrent/API/src/utils.cpp.i
.PHONY : AsciiMachineCurrent/API/src/utils.i

# target to preprocess a source file
AsciiMachineCurrent/API/src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/utils.cpp.i
.PHONY : AsciiMachineCurrent/API/src/utils.cpp.i

AsciiMachineCurrent/API/src/utils.s: AsciiMachineCurrent/API/src/utils.cpp.s
.PHONY : AsciiMachineCurrent/API/src/utils.s

# target to generate assembly for a file
AsciiMachineCurrent/API/src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ascii.dir/build.make CMakeFiles/Ascii.dir/AsciiMachineCurrent/API/src/utils.cpp.s
.PHONY : AsciiMachineCurrent/API/src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Ascii"
	@echo "... AsciiMachineCurrent/API/src/AsciiSignal.o"
	@echo "... AsciiMachineCurrent/API/src/AsciiSignal.i"
	@echo "... AsciiMachineCurrent/API/src/AsciiSignal.s"
	@echo "... AsciiMachineCurrent/API/src/Color.o"
	@echo "... AsciiMachineCurrent/API/src/Color.i"
	@echo "... AsciiMachineCurrent/API/src/Color.s"
	@echo "... AsciiMachineCurrent/API/src/Entity.o"
	@echo "... AsciiMachineCurrent/API/src/Entity.i"
	@echo "... AsciiMachineCurrent/API/src/Entity.s"
	@echo "... AsciiMachineCurrent/API/src/GUI_o.o"
	@echo "... AsciiMachineCurrent/API/src/GUI_o.i"
	@echo "... AsciiMachineCurrent/API/src/GUI_o.s"
	@echo "... AsciiMachineCurrent/API/src/Scene.o"
	@echo "... AsciiMachineCurrent/API/src/Scene.i"
	@echo "... AsciiMachineCurrent/API/src/Scene.s"
	@echo "... AsciiMachineCurrent/API/src/Server.o"
	@echo "... AsciiMachineCurrent/API/src/Server.i"
	@echo "... AsciiMachineCurrent/API/src/Server.s"
	@echo "... AsciiMachineCurrent/API/src/utils.o"
	@echo "... AsciiMachineCurrent/API/src/utils.i"
	@echo "... AsciiMachineCurrent/API/src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

